### ISSUE TITLE
Compose Multiplatform Support Plan？

### ISSUE THREAD

**Issue by panpf** [junerver/ComposeHooks#26]

**Comment by junerver** [comment]
Yes, I have plans to do this, but I don't know much about KMP at the moment. ComposeHooks has stabilized, and I will start trying KMP in the next month or two.

If you can help, it will be appreciated

**Comment by panpf** [comment]
目前我手头也有两个 Compose Mulitiplatform 项目正在开发中，没法抽出时间来从代码上帮你。

多平台相关的问题我们可以直接交流，相关的环境和配置你也可以直接参考我的多平台项目 https://github.com/panpf/sketch。

**Comment by junerver** [comment]
thanks，请问使用kmp你更推荐用什么IDE呢？Android Studio？IDEA？

我在使用Android Studio打开KMP项目时会出现一些类、函数爆红的情况：
![image](https://github.com/user-attachments/assets/3481de58-4309-4ded-8906-443e565f881a)

**Comment by panpf** [comment]
目前还是 Android Studio 更好，基本没啥问题。

**Comment by panpf** [comment]
你代码报红还是你环境配置有问题，相关插件都要用 jetbrains 版本的

**Comment by junerver** [comment]
T_T，好的，我学习一下，感谢，如果有问题需要向您请教我会在这个issue下留言

**Comment by panpf** [comment]
没得问题，一起为 Compose Multiplatform 生态添砖加瓦！

**Comment by junerver** [comment]
请教一个问题，我尝试将lib改造成kmp后，测试可以在项目中运行，但是当我使用[gradle-maven-publish-plugin](https://github.com/vanniktech/gradle-maven-publish-plugin)插件上传依赖库时，并没有生成多个target的包，还是如之前android lib一样的产物

我看您的项目也是使用的这个上传插件，请问是否需要进行额外的配置？

![image](https://github.com/user-attachments/assets/1fa3162e-0ca1-4f9c-9988-219692b8d9a6)

**Comment by panpf** [comment]
不需要什么特别的额外的配置，按照官方文档指示的配置即可。

一个正常的输出是这样的
![image](https://github.com/user-attachments/assets/209b1ca9-81fb-49f3-ac25-01cb502c0816)

你看看你的输出是否也是这样的，依赖的时候都是依赖 sketch-core 模块，这个模块配置了它支持哪些平台，gradle 会再去根据平台依赖具体平台的包

**Comment by junerver** [comment]
> 不需要什么特别的额外的配置，按照官方文档指示的配置即可。
> 
> 一个正常的输出是这样的 ![image](https://private-user-images.githubusercontent.com/3250512/365945062-209b1ca9-81fb-49f3-ac25-01cb502c0816.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5NTUwMzcsIm5iZiI6MTcyNTk1NDczNywicGF0aCI6Ii8zMjUwNTEyLzM2NTk0NTA2Mi0yMDliMWNhOS04MWZiLTQ5ZjMtYWMyNS0wMWNiNTAyYzA4MTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTBUMDc1MjE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWE2NGNlMDNmMjc3MDUzOTRkYWNmNTExZGU3NTBmYzM4Y2U3MTE2OWY1NThmOTIzNzhlYWUzYjc0ZGZlNDk2OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.PMHSIozHAvxlAsUWJs5-92nv5SsvRpXO2J-p7U5jnhM)
> 
> 你看看你的输出是否也是这样的，依赖的时候都是依赖 sketch-core 模块，这个模块配置了它支持哪些平台，gradle 会再去根据平台依赖具体平台的包

我的输出不是这样的，没生成这样的target目录，完全蒙圈了

**Comment by panpf** [comment]
你先打开 gradle 面板看看配置是否成功了，成功的话模块的 publishing 目录下面就会有各个平台的发布任务，像下面这样
![image](https://github.com/user-attachments/assets/0a5849e5-0510-409d-8a70-a4ce20382b21)

**Comment by junerver** [comment]
有一些，对比您图片中的少一些，我使用的是其中的`publishAllPublicationsToMavenCentralRepository`，但是推送到快照库中并没有这些target的目录；
[快照库](https://s01.oss.sonatype.org/content/repositories/snapshots/xyz/junerver/compose/hooks2/)
![image](https://github.com/user-attachments/assets/34bf65d2-489d-4c03-b78c-5d1687f35f64)

**Comment by junerver** [comment]
咦，好像成功了，我试试找个kmp项目依赖一下看看
![image](https://github.com/user-attachments/assets/f7f8aaa0-f27e-4021-97c5-2f1ddf09820d)

**Comment by junerver** [comment]
测试了下，好像没啥问题....
IDE爆红真的是让人惆怅，搞不明白为啥
![image](https://github.com/user-attachments/assets/7f09d878-58df-4ad0-a69a-63a93c30843f)

**Comment by panpf** [comment]
你这个截图我看只有 useBoolean 和 useConter 有红色下划线，应该只有他俩有问题，你看看提示什么信息

**Comment by junerver** [comment]
> 你这个截图我看只有 useBoolean 和 useCounter 有红色下划线，应该只有他俩有问题，你看看提示什么信息

可以编译运行，就是这些例如`@Composable`找不到引用，就很奇怪

**Comment by panpf** [comment]
你可以对比一下你的环境的版本和我的区别，代码之外的就是 Android Studio 升到最新 稳定版，jdk 就是 OpenJDK 17.0.7

**Comment by junerver** [comment]
windows上的as对kmp支持太差了，换到macos就没问题了😢
