### ISSUE TITLE
使用 Reducer 和 Context 拓展你的应用

### ISSUE THREAD

**Issue by danatechgithub4** [junerver/ComposeHooks#3]
详细步骤请看：https://zh-hans.react.dev/learn/scaling-up-with-reducer-and-context

TaskDemo.kt
```
package com.example.myapplication

import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.width
import androidx.compose.material3.Button
import androidx.compose.material3.Checkbox
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Surface
import androidx.compose.material3.Text
import androidx.compose.material3.TextField
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.key
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import com.example.myapplication.ui.theme.MyApplicationTheme

class TaskDemo : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent {
            MyApplicationTheme {
                // A surface container using the 'background' color from the theme
                Surface(modifier = Modifier.fillMaxSize(), color = MaterialTheme.colorScheme.background) {
                    TaskApp()
                }
            }
        }
    }
}

@Composable
fun TaskApp() {
    TasksProvider {
        Column {
            Text(text = "Day off in Kyoto", style = MaterialTheme.typography.titleLarge)
            AddTask()
            TaskList()
        }
    }
}

@Composable
fun AddTask() {
    var text by remember { mutableStateOf("") }
    val dispatch = useTasksDispatch()
    Row {
        TextField(
                modifier = Modifier.width(100.dp),
                value = text,
                onValueChange = { newText ->
                    text = newText
                },
                placeholder = { Text("Add task") }
        )
        Button(onClick = {
            dispatch(TaskAction.Added(text))
            text = ""
        }) {
            Text("Add")
        }
    }
}

@Composable
fun TaskList() {
    val tasks = useTasks()
    tasks.forEach { task ->
        key(task.id) {
            TaskItem(task = task)
        }
    }
}

@Composable
fun TaskItem(task: Task) {
    var isEditing by remember { mutableStateOf(false) }
    var text by remember { mutableStateOf(task.text) }

    val dispatch = useTasksDispatch()

    Row(verticalAlignment = Alignment.CenterVertically) {
        Checkbox(
                checked = task.done,
                onCheckedChange = { checked ->
                    dispatch(TaskAction.Changed(task.copy(done = checked)))
                }
        )

        if (isEditing) {
            TextField(
                    modifier = Modifier.width(100.dp),
                    value = text,
                    onValueChange = { newText ->
                        text = newText
                        dispatch(TaskAction.Changed(task.copy(text = newText)))
                    }
            )
            Button(onClick = { isEditing = false }) {
                Text("Save")
            }
        } else {
            Text(text = task.text)
            Button(onClick = { isEditing = true }) {
                Text("Edit")
            }
        }

        Button(onClick = {
            dispatch(TaskAction.Deleted(task.id))
        }) {
            Text("Delete")
        }
    }
}

data class Task(val id: Int, val text: String, val done: Boolean)

sealed interface TaskAction {
    data class Added(val text: String) : TaskAction
    data class Changed(val task: Task) : TaskAction
    data class Deleted(val taskId: Int) : TaskAction
}


```

TasksContext.kt
```
package com.example.myapplication

import androidx.compose.runtime.Composable
import xyz.junerver.compose.hooks.Reducer
import xyz.junerver.compose.hooks.createContext
import xyz.junerver.compose.hooks.useContext
import xyz.junerver.compose.hooks.useReducer

val TasksContext = createContext(emptyList<Task>())
val TasksDispatchContext = createContext<(TaskAction) -> Unit> {}

@Composable
fun TasksProvider(content: @Composable () -> Unit) {
    val (tasks, dispatch) = useReducer(listReducer, initialTasks)
    TasksContext.Provider(value = tasks) {
        TasksDispatchContext.Provider(value = dispatch) {
            content()
        }
    }
}

val listReducer: Reducer<List<Task>, TaskAction> =
        { prevState, action ->
            when (action) {
                is TaskAction.Added -> {
                    prevState + Task(nextId++, action.text, false)
                }
                is TaskAction.Changed -> {
                    prevState.map { if (it.id == action.task.id) action.task else it }
                }
                is TaskAction.Deleted -> {
                    prevState.filter { it.id != action.taskId }
                }
            }
        }

var nextId = 3
val initialTasks = listOf(
        Task(id = 0, text = "Philosopher’s Path", done = true),
        Task(id = 1, text = "Visit the temple", done = false),
        Task(id = 2, text = "Drink matcha", done = false)
)

@Composable
fun useTasks(): List<Task> {
    return useContext(TasksContext)
}

@Composable
fun useTasksDispatch(): (TaskAction) -> Unit {
    return useContext(TasksDispatchContext)
}
```

初学compose感谢作者提供丰富的脚手架！

请问作者目前这样结合使用 reducer 和 context还有什么问题或优化的地方吗？

**Comment by junerver** [comment]
> 详细步骤请看：https://zh-hans.react.dev/learn/scaling-up-with-reducer-and-context
> 
> TaskDemo.kt
> 
> ```
> package com.example.myapplication
> 
> import android.os.Bundle
> import androidx.activity.ComponentActivity
> import androidx.activity.compose.setContent
> import androidx.compose.foundation.layout.Column
> import androidx.compose.foundation.layout.Row
> import androidx.compose.foundation.layout.fillMaxSize
> import androidx.compose.foundation.layout.width
> import androidx.compose.material3.Button
> import androidx.compose.material3.Checkbox
> import androidx.compose.material3.MaterialTheme
> import androidx.compose.material3.Surface
> import androidx.compose.material3.Text
> import androidx.compose.material3.TextField
> import androidx.compose.runtime.Composable
> import androidx.compose.runtime.getValue
> import androidx.compose.runtime.key
> import androidx.compose.runtime.mutableStateOf
> import androidx.compose.runtime.remember
> import androidx.compose.runtime.setValue
> import androidx.compose.ui.Alignment
> import androidx.compose.ui.Modifier
> import androidx.compose.ui.unit.dp
> import com.example.myapplication.ui.theme.MyApplicationTheme
> 
> class TaskDemo : ComponentActivity() {
>     override fun onCreate(savedInstanceState: Bundle?) {
>         super.onCreate(savedInstanceState)
>         setContent {
>             MyApplicationTheme {
>                 // A surface container using the 'background' color from the theme
>                 Surface(modifier = Modifier.fillMaxSize(), color = MaterialTheme.colorScheme.background) {
>                     TaskApp()
>                 }
>             }
>         }
>     }
> }
> 
> @Composable
> fun TaskApp() {
>     TasksProvider {
>         Column {
>             Text(text = "Day off in Kyoto", style = MaterialTheme.typography.titleLarge)
>             AddTask()
>             TaskList()
>         }
>     }
> }
> 
> @Composable
> fun AddTask() {
>     var text by remember { mutableStateOf("") }
>     val dispatch = useTasksDispatch()
>     Row {
>         TextField(
>                 modifier = Modifier.width(100.dp),
>                 value = text,
>                 onValueChange = { newText ->
>                     text = newText
>                 },
>                 placeholder = { Text("Add task") }
>         )
>         Button(onClick = {
>             dispatch(TaskAction.Added(text))
>             text = ""
>         }) {
>             Text("Add")
>         }
>     }
> }
> 
> @Composable
> fun TaskList() {
>     val tasks = useTasks()
>     tasks.forEach { task ->
>         key(task.id) {
>             TaskItem(task = task)
>         }
>     }
> }
> 
> @Composable
> fun TaskItem(task: Task) {
>     var isEditing by remember { mutableStateOf(false) }
>     var text by remember { mutableStateOf(task.text) }
> 
>     val dispatch = useTasksDispatch()
> 
>     Row(verticalAlignment = Alignment.CenterVertically) {
>         Checkbox(
>                 checked = task.done,
>                 onCheckedChange = { checked ->
>                     dispatch(TaskAction.Changed(task.copy(done = checked)))
>                 }
>         )
> 
>         if (isEditing) {
>             TextField(
>                     modifier = Modifier.width(100.dp),
>                     value = text,
>                     onValueChange = { newText ->
>                         text = newText
>                         dispatch(TaskAction.Changed(task.copy(text = newText)))
>                     }
>             )
>             Button(onClick = { isEditing = false }) {
>                 Text("Save")
>             }
>         } else {
>             Text(text = task.text)
>             Button(onClick = { isEditing = true }) {
>                 Text("Edit")
>             }
>         }
> 
>         Button(onClick = {
>             dispatch(TaskAction.Deleted(task.id))
>         }) {
>             Text("Delete")
>         }
>     }
> }
> 
> data class Task(val id: Int, val text: String, val done: Boolean)
> 
> sealed interface TaskAction {
>     data class Added(val text: String) : TaskAction
>     data class Changed(val task: Task) : TaskAction
>     data class Deleted(val taskId: Int) : TaskAction
> }
> ```
> 
> TasksContext.kt
> 
> ```
> package com.example.myapplication
> 
> import androidx.compose.runtime.Composable
> import xyz.junerver.compose.hooks.Reducer
> import xyz.junerver.compose.hooks.createContext
> import xyz.junerver.compose.hooks.useContext
> import xyz.junerver.compose.hooks.useReducer
> 
> val TasksContext = createContext(emptyList<Task>())
> val TasksDispatchContext = createContext<(TaskAction) -> Unit> {}
> 
> @Composable
> fun TasksProvider(content: @Composable () -> Unit) {
>     val (tasks, dispatch) = useReducer(listReducer, initialTasks)
>     TasksContext.Provider(value = tasks) {
>         TasksDispatchContext.Provider(value = dispatch) {
>             content()
>         }
>     }
> }
> 
> val listReducer: Reducer<List<Task>, TaskAction> =
>         { prevState, action ->
>             when (action) {
>                 is TaskAction.Added -> {
>                     prevState + Task(nextId++, action.text, false)
>                 }
>                 is TaskAction.Changed -> {
>                     prevState.map { if (it.id == action.task.id) action.task else it }
>                 }
>                 is TaskAction.Deleted -> {
>                     prevState.filter { it.id != action.taskId }
>                 }
>             }
>         }
> 
> var nextId = 3
> val initialTasks = listOf(
>         Task(id = 0, text = "Philosopher’s Path", done = true),
>         Task(id = 1, text = "Visit the temple", done = false),
>         Task(id = 2, text = "Drink matcha", done = false)
> )
> 
> @Composable
> fun useTasks(): List<Task> {
>     return useContext(TasksContext)
> }
> 
> @Composable
> fun useTasksDispatch(): (TaskAction) -> Unit {
>     return useContext(TasksDispatchContext)
> }
> ```
> 
> 初学compose感谢作者提供丰富的脚手架！
> 
> 请问作者目前这样结合使用 reducer 和 context还有什么问题或优化的地方吗？

在ComposeHooks中已经提供了这二者组合的使用方式，没有必要再自己这样组合了，你可以参考：

- [在Compose中像使用redux一样轻松管理全局状态](https://juejin.cn/post/7352527589247336458)
- [在Compose中轻松使用异步dispatch管理全局状态](https://juejin.cn/post/7352785768094433289)
- [在Jetpack Compose中管理网络请求竟然如此简单！](https://juejin.cn/post/7353156196935434290)

**Comment by junerver** [comment]
在你的使用中其实可以只是用一个 context 向下暴露即可，没有必要通过 `createContext` 分别创建两个 context，这一点你可以参考 [useContext](https://github.com/junerver/ComposeHooks/blob/master/app/src/main/java/xyz/junerver/composehooks/example/UseContextExample.kt)
